image: node:lts-alpine

stages:
- devdeploy
- uatdeploy

before_script:
- apk add --no-cache aws-cli
- apk add tar


deploy-develop:
  when: manual
  stage: devdeploy
  script:
  - echo "building... "
  - npm install --progress=false --legacy-peer-deps
  - npm run lint || exit 1
  - npm run build -- --mode develop || exit 1
  - echo "Installing awscli..."
  - apk add --no-cache python3 py3-pip  && pip3 install --upgrade pip  && pip3 install --no-cache-dir awscli  && rm -rf /var/cache/apk/*
  - echo "Configuring awscli..."
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - aws configure set default.region ap-southeast-1
  - aws s3 sync dist s3://${DEV_S3_BUCKET}/ --delete --no-progress
  - aws cloudfront create-invalidation --distribution-id ${DEV_CLOUDFRONT_ID} --paths "/*"

  only:
  - develop
  tags:
  - node

deploy-uat:
  when: manual
  stage: uatdeploy
  script:
  - echo "building... "
  - npm install --progress=false --legacy-peer-deps
  - npm run lint || exit 1
  - npm run build -- --mode uat || exit 1
  - echo "Installing awscli..."
  - apk add --no-cache python3 py3-pip  && pip3 install --upgrade pip  && pip3 install --no-cache-dir awscli  && rm -rf /var/cache/apk/*
  - echo "Configuring awscli..."
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - aws configure set default.region ap-southeast-1
  - aws s3 sync dist s3://${UAT_S3_BUCKET}/ --delete --no-progress
  - aws cloudfront create-invalidation --distribution-id ${UAT_CLOUDFRONT_ID} --paths "/*"

  only:
  - uat
  tags:
  - node
